# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4befae92e56e4b97e853af5b1346d7251d466039adf001f5d295b1d39d8ee849f387e94f3a019f0865c1bd5a8c45da34489ace9f9a840d31904560a3921e448

test:
  secret_key_base: 704a21c5a0926f45f1288030ff6e81de5533ed4371a15d823b4c8d06cdff0394f43ea99a21e047ce7a4ffec7b3cafb2ded0b0dd70eb4a71dfd60ff0c36763240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
